function [aligned_data] = align_photometry_intan(varargin)
% align_photometry_intan - Aligns photometry data with Intan digital pulses.
%
% This function loads a processed photometry .mat file and an Intan 
% .pulses.events.mat file from the current directory (or specified), 
% calculates the temporal alignment, and saves a new synchronized dataset.
%
% Syntax:
%   aligned_data = align_photometry_intan()
%   aligned_data = align_photometry_intan('photometryFile', 'my_photo_data.mat')
%   aligned_data = align_photometry_intan('pulsesFile', 'my_intan_pulses.mat')
%
% Inputs:
%   (Optional name-value pairs)
%   'photometryFile' - Path to the .mat file generated by my_process_photometry_v6.
%                      If not provided, looks for *processed.mat or *photometry*.mat
%   'pulsesFile'     - Path to the .pulses.events.mat file generated by bz_getAnalogPulses.
%                      If not provided, looks for *.pulses.events.mat
%   'saveMat'        - Boolean, whether to save the output (default: true)
%
% Outputs:
%   aligned_data     - The photometry data structure with added aligned time fields.
%                      Saved to *_aligned.mat
%

    % --- Parse Inputs ---
    p = inputParser;
    addParameter(p, 'photometryFile', '', @ischar);
    addParameter(p, 'pulsesFile', '', @ischar);
    addParameter(p, 'saveMat', true, @islogical);
    parse(p, varargin{:});
    
    photometryFile = p.Results.photometryFile;
    pulsesFile = p.Results.pulsesFile;
    shouldSave = p.Results.saveMat;

    % --- 1. Locate and Load Photometry Data ---
    if isempty(photometryFile)
        % Try to find a likely file
        d = dir('*photometry*.mat');
        if isempty(d)
             d = dir('*processed.mat');
        end
        
        if isempty(d)
            error('No photometry .mat file found in pwd. Please specify ''photometryFile''.');
        elseif length(d) > 1
            warning('Multiple photometry files found. Using: %s', d(1).name);
        end
        photometryFile = d(1).name;
    end
    
    fprintf('Loading photometry data: %s\n', photometryFile);
    loaded_struct = load(photometryFile);
    
    % Extract the data structure (handle variable naming variations)
    if isfield(loaded_struct, 'data')
        photo_data = loaded_struct.data;
    else
        % Assume the first field is the data
        fields = fieldnames(loaded_struct);
        photo_data = loaded_struct.(fields{1});
    end

    % --- 2. Locate and Load Intan Pulse Events ---
    if isempty(pulsesFile)
        d = dir('*.pulses.events.mat');
        if isempty(d)
            error('No *.pulses.events.mat file found in pwd. Please Run bz_getAnalogPulses first.');
        elseif length(d) > 1
             warning('Multiple pulse files found. Using: %s', d(1).name);
        end
        pulsesFile = d(1).name;
    end
    
    fprintf('Loading Intan pulse events: %s\n', pulsesFile);
    loaded_pulses = load(pulsesFile);
    
    if isfield(loaded_pulses, 'pulses')
        intan_events = loaded_pulses.pulses;
    else
        fields = fieldnames(loaded_pulses);
        intan_events = loaded_pulses.(fields{1});
    end

    % --- 3. Perform Alignment ---
    
    % Photometry pulses: 'align_pulse_times' comes from my_process_photometry_v6
    % It is an Nx3 matrix where column 1 is start, col 2 is end, col 3 is duration.
    if isfield(photo_data, 'align_pulse_times')
        photo_pulse_times = photo_data.align_pulse_times(:,1); 
        photo_durations = photo_data.align_pulse_times(:,3);
    elseif isfield(photo_data, 'photometry_align')
        % Fallback: try to re-detect 
        threshold = 0.5 * max(photo_data.photometry_align); 
        temp_binary = photo_data.photometry_align > threshold;
        starts = find(diff(temp_binary) == 1);
        ends = find(diff(temp_binary) == -1);
        % Ensure same length
        min_len = min(length(starts), length(ends));
        photo_pulse_times = starts(1:min_len) / photo_data.sampling_rate;
        photo_durations = (ends(1:min_len) - starts(1:min_len)) / photo_data.sampling_rate;
    else
        error('Could not find alignment pulses in photometry data.');
    end

    % Intan pulses: 'timestamps' column 1 is start times
    intan_raw_times = intan_events.timestamps(:,1);
    
    % --- FILTERING / CLUSTERING STEP ---
    % Intan analog pulse detection often picks up noise or multiple spikes per pulse.
    % Strategy: 
    % 1. Sort timestamps
    % 2. Group pulses that are close together (e.g. within 200ms)
    % 3. Take the first timestamp of each group
    
    intan_raw_times = sort(intan_raw_times);
    
    if isempty(intan_raw_times)
        intan_pulse_times = [];
    else
        % Grouping threshold: Assume pulses are at least 0.2s apart
        inter_pulse_interval = diff(intan_raw_times);
        is_new_group = [true; inter_pulse_interval > 0.2]; 
        intan_pulse_times = intan_raw_times(is_new_group);
    end

    fprintf('  Clustering Intan pulses: reduced %d raw events to %d distinct events.\n', ...
        length(intan_raw_times), length(intan_pulse_times));
    
    % Optional: Filter by expected number of pulses if close
    if abs(length(intan_pulse_times) - length(photo_pulse_times)) > 5
         warning('Pulse count mismatch is still high (%d vs %d). Check your thresholds or recording.', ...
             length(intan_pulse_times), length(photo_pulse_times));
    end

    % Match number of pulses
    n_photo = length(photo_pulse_times);
    n_intan = length(intan_pulse_times);
    n_common = min(n_photo, n_intan);
    
    fprintf('  Photometry pulses: %d\n', n_photo);
    fprintf('  Intan pulses:      %d (after filtering)\n', n_intan);
    
    if n_common < 2
        error('Not enough pulses to align (Need at least 2). check filtering thresholds.');
    end

    % Warn if mismatch
    if n_photo ~= n_intan
        warning('Pulse count mismatch! Aligning using the first %d pulses.', n_common);
    end

    x = photo_pulse_times(1:n_common);  % Source (Photometry)
    y = intan_pulse_times(1:n_common);  % Target (Intan)

    % Linear Regression (y = m*x + c)
    b = polyfit(x, y, 1);
    slope = b(1);
    intercept = b(2);
    
    % Calculate residuals to check quality
    y_pred = polyval(b, x);
    residuals = y - y_pred;
    max_error = max(abs(residuals));

    fprintf('  Alignment Slope (Drift): %.8f\n', slope);
    fprintf('  Alignment Offset:        %.8f s\n', intercept);
    fprintf('  Max Residual Error:      %.8f s\n', max_error);
    
    if max_error > 0.05 % Warning if error > 50ms
        warning('Alignment error is high (%.2f ms). Check if pulse streams match.', max_error*1000);
    end
    
    % --- PLOT ALIGNMENT ---
    figure('Name', 'Alignment Verification', 'Position', [100, 100, 1000, 600]);
    
    subplot(2,1,1);
    plot(x, ones(size(x)), 'go', 'MarkerFaceColor', 'g'); hold on;
    plot(y, ones(size(y)), 'rx', 'LineWidth', 2);
    legend('Photometry (Original)', 'Intan (Target)');
    title(sprintf('Before Alignment (First %d pulses)', n_common));
    xlabel('Time (s)'); yticks([]);
    
    subplot(2,1,2);
    plot(x * slope + intercept, ones(size(x)), 'go', 'MarkerFaceColor', 'g'); hold on;
    plot(y, ones(size(y)), 'rx', 'LineWidth', 2); 
    legend('Photometry (Aligned)', 'Intan (Target)');
    title(sprintf('After Alignment (Max Error: %.1f ms)', max_error*1000));
    xlabel('Intan Time (s)'); yticks([]);


    % --- 4. Apply Alignment ---
    
    % Function to apply transform
    align_fn = @(t) t * slope + intercept;

    % Align time vector
    photo_data.time_seconds_aligned = align_fn(photo_data.time_seconds);
    
    % Align Event Times (Peaks/Troughs)
    if isfield(photo_data, 'FiveHT_peak_times'), photo_data.FiveHT_peak_times_aligned = align_fn(photo_data.FiveHT_peak_times); end
    if isfield(photo_data, 'FiveHT_trough_times'), photo_data.FiveHT_trough_times_aligned = align_fn(photo_data.FiveHT_trough_times); end
    if isfield(photo_data, 'Ach_peak_times'), photo_data.Ach_peak_times_aligned = align_fn(photo_data.Ach_peak_times); end
    if isfield(photo_data, 'Ach_trough_times'), photo_data.Ach_trough_times_aligned = align_fn(photo_data.Ach_trough_times); end
    
    % Align Trial Onset Times
    if isfield(photo_data, 'pulse_times')
         % Assuming pulse_times struct is [start, end, dur]
         photo_data.trial_start_times_aligned = align_fn(photo_data.pulse_times(:,1));
         photo_data.trial_end_times_aligned = align_fn(photo_data.pulse_times(:,2));
    end

    % Save alignment metadata
    photo_data.alignment.slope = slope;
    photo_data.alignment.intercept = intercept;
    photo_data.alignment.source_file = photometryFile;
    photo_data.alignment.target_file = pulsesFile;
    photo_data.alignment.max_residual = max_error;
    
    % Return aligned data
    aligned_data = photo_data;

    % --- 5. Save Results ---
    if shouldSave
        [~, name, ~] = fileparts(photometryFile);
        saveName = fullfile(pwd, [name '_aligned.mat']);
        save(saveName, 'aligned_data', 'intan_events');
        fprintf('Saved aligned data to: %s\n', saveName);
    end

end
